name: ghosts-toaster

networks:
  ghost_network:
    driver: bridge
  webhook_network:
    internal: true  # Only accessible by containers, not externally

services:
  # Caddy web server
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./static:/var/www/static:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ghost_network
    depends_on:
      - mysql
    env_file:
      - ./ghosts-toaster.env

  # Shared MySQL database for all Ghost instances
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./ghosts-toaster.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ghost_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis cache (optional, for performance)
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - ghost_network
    volumes:
      - redis_data:/data
      
  # Static site generator service with Git support
  static-generator:
    image: alpine:latest
    container_name: static-generator
    restart: unless-stopped
    volumes:
      - ./static:/output
      - ./scripts:/scripts
    networks:
      - ghost_network
      - webhook_network
    command: >
      sh -c "
        apk add --no-cache git nodejs npm ca-certificates && 
        npm install -g ghost-static-site-generator && 
        echo 'Static site generator container started' && 
        # Set git configuration
        git config --global user.email 'ghost-static@ghosts-toaster.local' &&
        git config --global user.name 'Ghost Static Generator' &&
        git config --global init.defaultBranch main &&
        # Keep container running
        tail -f /dev/null
      "
    
  # Webhook receiver for triggering static site generations
  webhook-receiver:
    image: node:18-alpine
    container_name: webhook-receiver
    restart: unless-stopped
    volumes:
      - ./webhook:/app
      - ./scripts:/scripts
      - ./sites:/sites:ro
    working_dir: /app
    networks:
      - ghost_network
      - webhook_network
    depends_on:
      - static-generator
    command: sh -c "npm install && node webhook-server.js"
    environment:
      - PORT=9000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-changeme}

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
  redis_data:

# Include all site-specific compose files
# Each file should be named after the site's hostname
include:
  - include-sites.yml
