name: ghosts-toaster

networks:
  ghost_network:
    driver: bridge
  webhook_network:
    internal: true  # Only accessible by containers, not externally

services:
  # Caddy web server
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-sites:/etc/caddy/caddy-sites:ro
      - ./static:/var/www/static:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ghost_network
    depends_on:
      - mysql
    env_file:
      - ./ghosts-toaster.env

  # Shared MySQL database for all Ghost instances
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./ghosts-toaster.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ghost_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis cache (optional, for performance)
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - ghost_network
    volumes:
      - redis_data:/data
      
  # Static site generator service with Git support
  static-generator:
    image: alpine:latest
    container_name: static-generator
    restart: unless-stopped
    volumes:
      - ./static:/static:rw
      - ./scripts:/scripts
      - ./ssh:/root/.ssh:rw
    networks:
      - ghost_network
      - webhook_network
    command: >
      sh -c "
        apk add --no-cache git nodejs npm ca-certificates wget openssh-client &&
        apk add --no-cache bash python3 py3-pip py3-pkgconfig python3-dev gcc musl-dev linux-headers pkgconfig libxml2-dev &&
        pip install --root-user-action=ignore --break-system-packages git+https://github.com/ArchiveTeam/ludios_wpull@5.0.3 &&
        npm install -g github:inconceivableza/ghost-static-site-generator &&
        # Initialize ssh keys
        [ -f /root/.ssh/id_ed25519 ] || ssh-keygen -N '' -t ed25519 -C '${SSH_KEY_NAME:-static-generator@ghosts-toaster.local}' -f /root/.ssh/id_ed25519
        echo 'Static site generator container started' && 
        # Set git configuration
        git config --global user.email 'ghost-static@ghosts-toaster.local' &&
        git config --global user.name 'Ghost Static Generator' &&
        git config --global init.defaultBranch main &&
        # Keep container running
        tail -f /dev/null
      "
    
  # Webhook receiver for triggering static site generations
  webhook-receiver:
    image: node:18-alpine
    container_name: webhook-receiver
    restart: unless-stopped
    volumes:
      - ./webhook:/app
      - ./scripts:/scripts
      - ./sites:/sites:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    networks:
      ghost_network:
        aliases:
          - webhook-receiver.docker.internal
      webhook_network: {}
    depends_on:
      - static-generator
    command: sh -c "apk add --no-cache docker-cli bash && npm install && node webhook-server.js"
    environment:
      - PORT=9000
    env_file:
      - ./ghosts-toaster.env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      TZ: "UTC"
    restart: unless-stopped
    env_file:
      - ./ghosts-toaster.env

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
  redis_data:

# Include all site-specific compose files
# Each file should be named after the site's hostname
include:
  - include-sites.yml
