version: '3.8'

services:
  ghost_${SITE_NAME}:
    image: ghost:5-alpine
    container_name: ghost_${SITE_NAME}
    restart: unless-stopped
    environment:
      # Ghost configuration
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      url: https://${SITE_DOMAIN}
      NODE_ENV: production
      
      # Optional mail configuration
      mail__transport: ${MAIL_TRANSPORT:-SMTP}
      mail__options__service: ${MAIL_SERVICE:-Mailgun}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
    volumes:
      - ghost_content_${SITE_NAME}:/var/lib/ghost/content
    networks:
      - ghost_network
    depends_on:
      - mysql

volumes:
  ghost_content_${SITE_NAME}:

networks:
  ghost_network:
    external: true
