services:
  ghost_${SITE_NAME}:
    image: ghost:5-alpine
    container_name: ghost_${SITE_NAME}
    restart: unless-stopped
    environment:
      # Ghost configuration
      # these parameters are defined in site.env and passed in from include-sites.yml
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      url: https://${SITE_DOMAIN}
      NODE_ENV: production
      # mail__ configuration is defined in global environment
    volumes:
      - ghost_content_${SITE_NAME}:/var/lib/ghost/content
    networks:
      - ghost_network
    depends_on:
      - mysql
    env_file:
      - ../../.env
    labels:
      group: ghost
    depends_on:
      - mysql
      - redis
      - caddy

volumes:
  ghost_content_${SITE_NAME}:
